// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKeyProtectionPolicy } from "./DeviceKeyProtectionPolicy";

/**
 * Create or load a controller-local device key for this account/client binding.
 */
export type DeviceKeyCreateParams = { accountUserId: string, clientId: string,
/**
 * Defaults to `hardware_only` when omitted.
 */
protectionPolicy?: DeviceKeyProtectionPolicy | null, };
